name: CI/CD n8n Deployment

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t votre-dockerhub-username/n8n:latest .

      - name: Push Docker image
        run: |
          docker push votre-dockerhub-username/n8n:latest

      - name: Connect to VPS and deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Préparer l’environnement si nécessaire
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker $USER
            fi
            # Cloner ou mettre à jour le script de déploiement
            echo "Vérification et permissions du script"
            chmod +x ~/deploy_n8n.sh
            # Exécuter le déploiement
            ~/deploy_n8n.sh
