name: CI/CD n8n Deployment

on:
  push:
    branches:
      - main  # La branche principale

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t votre-dockerhub-username/n8n:latest .

      - name: Push Docker image
        run: |
          docker push votre-dockerhub-username/n8n:latest

      - name: Deploy n8n on VPS via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ~/  # ou le répertoire où vous avez mis deploy_n8n.sh
            ./deploy_n8n.sh

