name: CI/CD n8n - Build, Test, Push, Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1. Pousser l'image officielle ou personnalisée
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Si tu veux utiliser l’image officielle sans build, saute cette étape
      - name: (Optionnel) Build personnalisé de l’image
        run: |
          docker pull n8nio/n8n:latest
          # Si tu veux faire une build custom, décommente ci-dessous
          # docker build -t ton-utilisateur/n8n:latest .

  # 2. Tester l’image
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test Docker image
        run: |
          docker run -d --name test_n8n -p 5678:5678 n8nio/n8n:latest
          sleep 10
          if curl -fsS http://localhost:5678; then
            echo "Test réussi"
            docker stop test_n8n
            docker rm test_n8n
          else
            echo "Échec du test"
            docker logs test_n8n || true
            docker stop test_n8n || true
            docker rm test_n8n
            exit 1
          fi

  # 3. Pousser l’image (si build personnalisé)
  push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push images
        run: |
          docker push n8nio/n8n:latest
          # Si build personnalisé, pousser aussi ton image
          # docker push ton-utilisateur/n8n:latest

  # 4. Déploiement sur ton VPS
  deploy:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: Transfer and run deploy script
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 167.86.88.17 # Adresse IP du VPS en dur
          username: ${{ secrets.VPS_ADMIN_USER }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          port: 22
          script: |
            set -e

            # Installer Docker si nécessaire
            if ! command -v docker > /dev/null; then
              apk add --no-cache curl bash
              curl -fsSL https://get.docker.com | sh
              addgroup docker
              adduser -D ${DEPLOY_USER}
              adduser ${DEPLOY_USER} docker
            fi

            # Vérifier et copier le script de déploiement
            scp -o StrictHostKeyChecking=no deploy_n8n.sh ${DEPLOY_USER}@167.86.88.17:/home/${DEPLOY_USER}/deploy_n8n.sh
            ssh -o StrictHostKeyChecking=no ${DEPLOY_USER}@167.86.88.17 "chmod +x /home/${DEPLOY_USER}/deploy_n8n.sh"

            # Exécuter le script pour déployer la nouvelle image
            ssh -o StrictHostKeyChecking=no ${DEPLOY_USER}@167.86.88.17 "/home/${DEPLOY_USER}/deploy_n8n.sh n8nio/n8n:latest"
