name: CI/CD n8n - Build, Push, Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: wezoun/n8n:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Transfer and run deploy script
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 167.86.88.17 # Remplacez par l'IP de votre VPS
          username: ${{ secrets.VPS_ADMIN_USER }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          port: 22
          script: |
            set -e
            # Copier le script deploy_n8n.sh depuis GitHub vers le VPS
            scp -o StrictHostKeyChecking=no ./scripts/deploy_n8n.sh ${DEPLOY_USER}@167.86.88.17:/home/${DEPLOY_USER}/deploy_n8n.sh
            # Rendre le script exécutable
            ssh -o StrictHostKeyChecking=no ${DEPLOY_USER}@167.86.88.17 "chmod +x /home/${DEPLOY_USER}/deploy_n8n.sh"
            # Exécuter le script de déploiement
            ssh -o StrictHostKeyChecking=no ${DEPLOY_USER}@167.86.88.17 "/home/${DEPLOY_USER}/deploy_n8n.sh wezoun/n8n:latest"
